---
title: "Dplyr Advanced"
output: html_notebook
---


```{r}
library(dplyr)
library(readr)
billboard100 <- read_csv("billboard100.csv")
```
```{r}
music_df = billboard100 %>%
  select(date:artist, weeks_popular='weeks-on-board')
music_df
```

```{r}
library(lubridate)
library(stringr)
```


```{r}
music_df.cleaned = 
  music_df %>%
  mutate(date = mdy(date),
         primary_artist = ifelse(str_detect(artist, 'Featuring'),
                                 str_match(artist, '(.*)\\sFeaturing')[,2],
                                 artist),
         featured_artist = str_match(artist, 'Featuring\\s(.*)')[,2])
```

```{r}
library(tidyr)
```

```{r}
music_df.cleaned %>%
  distinct(song, primary_artist, featured_artist) %>%
  pivot_longer(2:3, names_to="artist_type", values_to="artist_name") %>%
  filter(artist_name=="Drake") %>%
  count(artist_type)
```

```{r}
music_df.cleaned %>%
  filter(rank <= 3) %>%
  select(date, rank, song) %>%
  pivot_wider(names_from="rank",values_from="song")
```


```{r}
mtv_data = read_csv("mtv")
```

```{r}
top5_genres = music_df.cleaned %>%
  inner_join(mtv_data, by = c("primary_artist" = "name")) %>%
  select(song, primary_artist, genre) %>%
  filter(!is.na(genre)) %>%
  distinct() %>%
  count(genre) %>%
  top_n(5) %>%
  pull(genre)
```

```{r}
library(ggplot2)
```

```{r}
music_df.cleaned %>%
  inner_join(mtv_data, by = c("primary_artist" = "name")) %>%
  mutate(date=floor_date(date, unit="year")) %>%
  select(date, song, genre) %>%
  filter(genre %in% top5_genres) %>%
  count(date, genre) %>%
  ggplot(aes(x=date,y=n,color=genre)) + geom_line()
```





